name: Trigger Build

on:
  push:
    branches:
      - main  # or the branch you want to monitor

jobs:
  trigger_repo_b:
    runs-on: ubuntu-latest

    steps:
    - name: Send a repository dispatch to Repo B
      run: |
        curl -X POST \
        -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
        -H "Accept: application/vnd.github.everest-preview+json" \
        https://api.github.com/repos/Sokcevic/nvim-build/dispatches \
        -d '{"event_type":"build_nvim_image"}'
